In [5]:
import numpy as np
dt = np.dtype(np.int32)
print(dt)
print(type(dt))

int32
<class 'numpy.dtypes.Int32DType'>


# Ndarray对象

+ random.randn()

  返回一个或一组样本具有标准正态分布

In [2]:
import numpy as np
arr = np.random.randn()
print(arr)

-0.4685008527245723


In [3]:
arr = np.random.random(3)
arr

array([0.96010582, 0.05245608, 0.4960729 ])

In [4]:
arr = np.random.randn(2,5)
print(arr)

[[ 0.39887463  0.96037728 -1.3752713   0.15263841  1.31720042]
 [-0.94726242  1.27486387  0.36501577 -0.08499861  1.14395459]]


In [6]:
arr = np.random.normal(loc=1,scale=2,size=5)
arr

array([ 0.51256656, -2.44884444,  2.5960496 , -2.32170261,  1.73971355])

+ np.random.randint(1,100,10)

In [23]:
array1 = np.random.randint(1, 100, 10)
array1

array([72, 16, 41, 25, 91, 40, 45, 67, 92, 31])

+ 和，均值，中位数，

  > **说明**：上面代码中的`mean`、`median`和`quantile`分别是 NumPy 中计算算术平均值、中位数和分位数的函数，其中`quantitle`函数的第二个参数设置为0.5表示计算50%分位数，也就是中位数。

In [24]:
print(array1.sum())
print(np.sum(array1))
print(array1.mean())
print(np.mean(array1))
print(np.median(array1))
print(np.quantile(array1, 0.5))

520
520
52.0
52.0
43.0
43.0


# ndarray 数组
## 创建数组

In [2]:
import numpy as np

# 通过数组创建
array1 = np.array([1, 2, 3, 4, 5])
print(array1)

# 通过划定范围
array3 = np.arange(0, 20, 2)
print(array3)

arr = np.arange(24)
print(arr)
# 维度
print(arr.ndim)

arr2 = arr.reshape(2,3,4)
print(arr2)
print(arr2.ndim)

[1 2 3 4 5]
[ 0  2  4  6  8 10 12 14 16 18]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
3


In [3]:
# 方法三：使用`linspace`函数，用指定范围和元素个数创建数组对象，生成等差数列
array4 = np.linspace(-1, 1, 11)
print(array4)

[-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1. ]


In [6]:
# 使用`logspace`函数，生成等比数列
array5 = np.logspace(1, 10, num=10, base=2)
array5

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

> 除此之外还有其他方法

## 数组对象的属性

+ `size` 获取数组元素个数。
+ `ndim`属性：获取数组的维度。
+ `shape`属性：获取数组的形状。
+ `dtype`属性：获取数组元素的数据类型。
+ `itemsize`属性：获取数组单个元素占用内存空间的字节数。
+ `nbytes`属性：获取数组所有元素占用内存空间的字节数。

In [3]:
import numpy as np

array17 = np.arange(1, 100, 2)
array18 = np.random.rand(3, 4)
print(array17.size)
print(array18.size)

50
12


## 索引计算

### 普通索引

In [7]:
array19 = np.arange(1, 10)
print(array19)
print(array19[0], array19[array19.size - 1])
print(array19[-array19.size], array19[-1])

[1 2 3 4 5 6 7 8 9]
1 9
1 9


In [10]:
array20 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array20[2]

array([7, 8, 9])

### 切片索引

切片索引是形如`[开始索引:结束索引:跨度]`的语法，通过指定**开始索引**（默认值无穷小）、**结束索引**（默认值无穷大）和**跨度**（默认值1），从数组中取出指定部分的元素并构成新的数组。因为开始索引、结束索引和步长都有默认值，所以它们都可以省略，如果不指定步长，第二个冒号也可以省略。一维数组的切片运算跟 Python 中的`list`类型的切片非常类似，此处不再赘述，二维数组的切片可以参考下面的代码，相信非常容易理解。

In [13]:
array20[:2, 1:]
array20[::-2, ::-2]

array([[9, 7],
       [3, 1]])

#### 花式索引

花式索引是用保存整数的数组充当一个数组的索引，这里所说的数组可以是 NumPy 的`ndarray`，也可以是 Python 中`list`、`tuple`等可迭代类型，可以使用正向或负向索引。

In [14]:
arr = array19[[0, 1, 1, -1, 4, -1]]
print(arr)

[1 2 2 9 5 9]


In [20]:
arr = array20[[0, 2], [1, 2]]
print(arr)

[2 9]


## 布尔索引

In [21]:
array19[[True, True, False, False, True, False, False, True, True]]

array([1, 2, 5, 8, 9])