# 学前班

## 张量

In [2]:
import torch
import numpy as np

1. 直接引入

In [3]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

2. np导入

In [5]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

3. 使用其他的tensor导入

In [6]:
x_ones = torch.ones_like(x_data)   # 保留 x_data 的属性
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)   # 重写 x_data 的数据类型：int -> float
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8622, 0.8230],
        [0.2171, 0.1911]]) 



4. 使用维度随机构造张量

In [7]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.6115, 0.2992, 0.8743],
        [0.7942, 0.0709, 0.4326]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## 张量的属性

In [9]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## 张量的运算

+ 加法
+ 乘积和矩阵乘法

In [11]:
# 逐个元素相乘结果
print(f"tensor.mul(tensor): \n {tensor.mul(tensor)} \n")
# 等价写法:
print(f"tensor * tensor: \n {tensor * tensor}")

tensor.mul(tensor): 
 tensor([[0.0009, 0.7582, 0.0275, 0.1456],
        [0.7277, 0.1598, 0.0249, 0.1442],
        [0.4733, 0.7593, 0.3654, 0.3731]]) 

tensor * tensor: 
 tensor([[0.0009, 0.7582, 0.0275, 0.1456],
        [0.7277, 0.1598, 0.0249, 0.1442],
        [0.4733, 0.7593, 0.3654, 0.3731]])


In [12]:
print(f"tensor.matmul(tensor.T): \n {tensor.matmul(tensor.T)} \n")
# 等价写法:
print(f"tensor @ tensor.T: \n {tensor @ tensor.T}")

tensor.matmul(tensor.T): 
 tensor([[0.9322, 0.5450, 1.1129],
        [0.5450, 1.0566, 1.2626],
        [1.1129, 1.2626, 1.9711]]) 

tensor @ tensor.T: 
 tensor([[0.9322, 0.5450, 1.1129],
        [0.5450, 1.0566, 1.2626],
        [1.1129, 1.2626, 1.9711]])


## Tensor与Numpy的转化

> 张量和Numpy array数组在CPU上可以共用一块内存区域, 改变其中一个另一个也会随之改变。

1. 由张量变换为Numpy array数组

In [14]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


2. 由Numpy array数组转为张量

In [15]:
n = np.ones(5)
t = torch.from_numpy(n)

In [16]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
