In [4]:
import numpy as np
array1 = np.arange(1, 10)
print(array1 + 10)
print(array1 * 10)

[11 12 13 14 15 16 17 18 19]
[10 20 30 40 50 60 70 80 90]


In [5]:
print(array1 > 5)
print(array1 % 2 == 0)

[False False False False False  True  True  True  True]
[False  True False  True False  True False  True False]


In [6]:
array2 = np.array([1, 1, 1, 2, 2, 2, 3, 3, 3])
print(array1 + array2)
print(array1 * array2)
print(array1 ** array2)

[ 2  3  4  6  7  8 10 11 12]
[ 1  2  3  8 10 12 21 24 27]
[  1   2   3  16  25  36 343 512 729]


# 兼容

In [7]:
array5 = np.array([[0, 0, 0], [1, 1, 1], [2, 2, 2], [3, 3, 3]])
array6 = np.array([1, 2, 3])
array5 + array6

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])