In [2]:
import numpy as np

a = np.array([1,2,3])
b = np.array([2,3,4])
# 矩阵的点乘
print(str(np.dot(a,b)))


20


In [3]:
np.log(4)

1.3862943611198906

In [5]:
xvalues = np.array([1, 2, 3, 4])
yvalues = np.array([7, 6, 5])

xx, yy = np.meshgrid(xvalues.T, yvalues)

print('xx=', xx)
print('yy=', yy)

xx= [[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
yy= [[7 7 7 7]
 [6 6 6 6]
 [5 5 5 5]]


In [9]:
xvalues = np.array([[1, 2, 3, 4],[7, 6, 5,8]])
xvalues.reshape(4,2)
# print(xvalues)

array([[1, 2],
       [3, 4],
       [7, 6],
       [5, 8]])